const test=require('node:test');
const assert=require('node:assert/strict');
const {fixture,office,settled,html}=require('./app-harness.cjs');
test('open modal dialogs lock root and page scrolling',()=>assert.match(html,/html:has\(dialog:modal\),\s*body:has\(dialog:modal\)\s*\{\s*overflow:\s*hidden/));
test('confirmation keeps its header fixed and scrolls its constrained body',()=>{assert.match(html,/#appConfirmDialog\[open\]\s*\{[^}]*display:\s*flex[^}]*flex-direction:\s*column/);assert.match(html,/#appConfirmDialog\s+\.app-confirm-header\s*\{[^}]*flex:\s*0 0 auto/);assert.match(html,/#appConfirmDialog\s+\.app-confirm-body\s*\{[^}]*min-height:\s*0[^}]*overflow:\s*auto/);});
test('narrow title wraps its version without shrinking actions',()=>{assert.match(html,/@media\s*\(max-width:\s*420px\)[\s\S]*?\.brand-name\s*\{[^}]*flex-wrap:\s*wrap[^}]*white-space:\s*normal[^}]*overflow:\s*visible/);assert.match(html,/\.header-actions\s*\{\s*flex-shrink:\s*0/);});
async function begin(){const f=await fixture();f.api.addFiles([await office()]);await settled(f);f.get('#clear-button').focus();const clearing=f.get('#clear-button').dispatch('click');return {f,clearing};}
test('affirmative Clear focuses the enabled Choose files control after rendering',async()=>{const {f,clearing}=await begin();await f.get('#appConfirmOk').dispatch('click');await clearing;assert.equal(f.api.records.length,0);assert.equal(f.get('#clear-button').disabled,true);assert.equal(f.document.activeElement,f.get('#choose-button'));assert.notEqual(f.document.activeElement.focusOptions?.preventScroll,true);});
for(const action of ['#appConfirmCancel','#appConfirmClose'])test(`${action} preserves files and original Clear focus`,async()=>{const {f,clearing}=await begin();await f.get(action).dispatch('click');await clearing;assert.equal(f.api.records.length,1);assert.equal(f.document.activeElement,f.get('#clear-button'));});
for(const blocked of ['modal','hidden','disconnected'])test(`successful Clear does not steal focus when ${blocked}`,async()=>{const {f,clearing}=await begin();const chosen=f.get('#choose-button');if(blocked==='hidden')chosen.hidden=true;if(blocked==='disconnected')chosen.isConnected=false;const owner=f.get('#helpDialog');if(blocked==='modal')owner.showModal();await f.get('#appConfirmOk').dispatch('click');await clearing;assert.notEqual(f.document.activeElement,chosen);});
